export const JOIN = "JOIN";
export const JOIN_ACKNOWLEDGE = "JOIN_ACKNOWLEDGE";
export const ADD_MEMBER = "ADD_MEMBER";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const MAKE_SUBCLIENT_MAINCLIENT = "MAKE_SUBCLIENT_MAINCLIENT";
export const ADD_OBJECT = "ADD_OBJECT";
export const MAKE_THE_MEMBER_MAINCLIENT = "MAKE_THE_MEMBER_MAINCLIENT";
export const REMOVE_OBJECT = "REMOVE_OBJECT";
