export const JOIN = "JOIN";
export const JOIN_ACKNOWLEDGE = "JOIN_ACKNOWLEDGE";
export const ADD_MEMBER = "ADD_MEMBER";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const MAKE_SUBCLIENT_MAINCLIENT = "MAKE_SUBCLIENT_MAINCLIENT";
